# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
# From scientific-python.org

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - gfortran
    - libfftw3-dev
  jobs:
    pre_build:
      - git clone --depth 1 https://github.com/wasjabloch/relmt-data.git /tmp/relmt-data
      # Copy executed notebooks into your docs tree (choose the path you prefer)
      - cp /tmp/relmt-data/notebooks/*.ipynb examples/

sphinx:
  configuration: docs/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev
